[package]
name = "ch_16_2_messages"
version = "0.1.0"
authors = ["basicdays <info@basicdays.com>"]
edition = "2021"
default-run = "ch_16_2_messages"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
