[package]
name = "ch_11_1_tests"
version = "0.1.0"
authors = ["basicdays <info@basicdays.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
