[package]
name = "ch_16_3_shared_state"
version = "0.1.0"
authors = ["basicdays <info@basicdays.com>"]
edition = "2018"
default-run = "ch_16_3_shared_state"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
